export type Product = {
    id:number
    title: string
    price: number
    rating?: number
    describtion?: string
    color?: string
    pack?: string
    material?: string
    length?: string
    stock?: number
    categories: string
    image: string
}

const productsArray: Product[] = [
{
    id:1,
    title: 'Large candle',
    price: 10,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '2pcks',
    stock: 10,
    categories: 'candles',
    image: "/images/product-large.jpg",
},
{
    id:2,
    title: 'Large candle',
    price: 15,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '3pcks',
    stock: 10,
    categories: 'candles',
    image: "/images/product-large.jpg",
},
{
    id:3,
    title: 'Large candle',
    price: 20,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '4pcks',
    stock: 10,
    categories: 'candles',
    image: "/images/product-large.jpg",
},
{
    id:4,
    title: 'Scented candles',
    price: 80,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '35cm',
    stock: 50,
    categories: 'candles',
    image: "/images/product-scented.jpg",
},
{
    id:5,
    title: 'Scented candles',
    price: 85,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '40cm',
    stock: 50,
    categories: 'candles',
    image: "/images/product-scented.jpg",
},
{
    id:6,
    title: 'Scented candles',
    price: 90,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '45cm',
    stock: 50,
    categories: 'candles',
    image: "/images/product-scented.jpg",
},
{
    id:7,
    title: 'Scented candles',
    price: 60,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '35cm',
    stock: 50,
    categories: 'candles',
    image: "/images/product-scented.jpg",
},
{
    id:8,
    title: 'Scented candles',
    price: 65,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '40cm',
    stock: 50,
    categories: 'candles',
    image: "/images/product-scented.jpg",
},
{
    id:9,
    title: 'Scented candles',
    price: 70,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '45cm',
    stock: 50,
    categories: 'candles',
    image: "/images/product-scented.jpg",
},
{
    id:10,
    title: 'Scented candles',
    price: 40,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '35cm',
    stock: 50,
    categories: 'candles',
    image: "/images/product-scented.jpg",
},
{
    id:11,
    title: 'Scented candles',
    price: 45,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '40cm',
    stock: 50,
    categories: 'candles',
    image: "/images/product-scented.jpg",
},
{
    id:12,
    title: 'Scented candles',
    price: 50,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '45cm',
    stock: 50,
    categories: 'candles',
    image: "/images/product-scented.jpg",
},
{
    id:13,
    title: 'Eucalyptus candle',
    price: 12,
    rating: 5,
    describtion: '',
    stock: 10,
    categories: 'candles',
    image: "/images/product-eucalyptus.jpg",
},
{
    id:14,
    title: 'Ceramic creamer',
    price: 80,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-creamer.jpg",
},
{
    id:15,
    title: 'Ceramic creamer',
    price: 85,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-creamer.jpg",
},
{
    id:16,
    title: 'Ceramic creamer',
    price: 90,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-creamer.jpg",
},
{
    id:17,
    title: 'Ceramic creamer',
    price: 60,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-creamer.jpg",
},
{
    id:18,
    title: 'Ceramic creamer',
    price: 65,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-creamer.jpg",
},
{
    id:19,
    title: 'Ceramic creamer',
    price: 70,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-creamer.jpg",
},
{
    id:20,
    title: 'Ceramic creamer',
    price: 40,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-creamer.jpg",
},
{
    id:21,
    title: 'Ceramic creamer',
    price: 45,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-creamer.jpg",
},
{
    id:22,
    title: 'Ceramic creamer',
    price: 50,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-creamer.jpg",
},
{
    id:23,
    title: 'Ceramic plates',
    price: 80,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-plates.jpg",
},
{
    id:24,
    title: 'Ceramic plates',
    price: 85,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-plates.jpg",
},
{
    id:25,
    title: 'Ceramic plates',
    price: 90,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-plates.jpg",
},
{
    id:26,
    title: 'Ceramic plates',
    price: 50,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-plates.jpg",
},
{
    id:27,
    title: 'Ceramic plates',
    price: 55,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-plates.jpg",
},
{
    id:28,
    title: 'Ceramic plates',
    price: 60,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-plates.jpg",
},
{
    id:29,
    title: 'Ceramic plates',
    price: 40,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-plates.jpg",
},
{
    id:30,
    title: 'Ceramic plates',
    price: 45,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-plates.jpg",
},
{
    id:31,
    title: 'Ceramic plates',
    price: 50,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-plates.jpg",
},
{
    id:32,
    title: 'Ceramic bowls',
    price: 80,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-bowls.jpg",
},
{
    id:33,
    title: 'Ceramic bowls',
    price: 85,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-bowls.jpg",
},
{
    id:34,
    title: 'Ceramic bowls',
    price: 90,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-bowls.jpg",
},
{
    id:35,
    title: 'Ceramic bowls',
    price: 60,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-bowls.jpg",
},
{
    id:36,
    title: 'Ceramic bowls',
    price: 65,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-bowls.jpg",
},
{
    id:37,
    title: 'Ceramic bowls',
    price: 70,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-bowls.jpg",
},
{
    id:38,
    title: 'Ceramic bowls',
    price: 40,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-bowls.jpg",
},
{
    id:39,
    title: 'Ceramic bowls',
    price: 45,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-bowls.jpg",
},
{
    id:40,
    title: 'Ceramic bowls',
    price: 50,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-bowls.jpg",
},
{
    id:41,
    title: 'Ceramic birds',
    price: 80,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_birds.jpg",
},
{
    id:42,
    title: 'Ceramic birds',
    price: 85,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_birds.jpg",
},
{
    id:43,
    title: 'Ceramic birds',
    price: 90,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_birds.jpg",
},
{
    id:44,
    title: 'Ceramic birds',
    price: 60,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_birds.jpg",
},
{
    id:45,
    title: 'Ceramic birds',
    price: 65,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_birds.jpg",
},
{
    id:46,
    title: 'Ceramic birds',
    price: 70,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_birds.jpg",
},
{
    id:47,
    title: 'Ceramic birds',
    price: 40,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_birds.jpg",
},
{
    id:48,
    title: 'Ceramic birds',
    price: 45,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_birds.jpg",
},
{
    id:49,
    title: 'Ceramic birds',
    price: 50,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_birds.jpg",
},
{
    id:50,
    title: 'Ceramic mug',
    price: 80,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_mug.jpg",
},
{
    id:51,
    title: 'Ceramic mug',
    price: 85,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_mug.jpg",
},
{
    id:52,
    title: 'Ceramic mug',
    price: 90,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_mug.jpg",
},
{
    id:53,
    title: 'Ceramic mug',
    price: 60,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_mug.jpg",
},
{
    id:54,
    title: 'Ceramic mug',
    price: 65,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_mug.jpg",
},
{
    id:55,
    title: 'Ceramic mug',
    price: 70,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_mug.jpg",
},
{
    id:56,
    title: 'Ceramic mug',
    price: 40,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_mug.jpg",
},
{
    id:57,
    title: 'Ceramic mug',
    price: 45,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_mug.jpg",
},
{
    id:58,
    title: 'Ceramic mug',
    price: 50,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_mug.jpg",
},
{
    id:59,
    title: 'Ceramic pot',
    price: 80,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_pot.jpg",
},
{
    id:60,
    title: 'Ceramic pot',
    price: 85,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_pot.jpg",
},
{
    id:61,
    title: 'Ceramic pot',
    price: 90,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Gold",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_pot.jpg",
},
{
    id:62,
    title: 'Ceramic pot',
    price: 60,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "35cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_pot.jpg",
},
{
    id:63,
    title: 'Ceramic pot',
    price: 65,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_pot.jpg",
},
{
    id:64,
    title: 'Ceramic pot',
    price: 70,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Platinum",
    length: "45cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_pot.jpg",
},
{
    id:65,
    title: 'Ceramic pot',
    price: 40,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_pot.jpg",
},
{
    id:66,
    title: 'Ceramic pot',
    price: 45,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_pot.jpg",
},
{
    id:67,
    title: 'Ceramic pot',
    price: 50,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: "Silver",
    length: "40cm",
    stock: 50,
    categories: 'ceramics',
    image: "/images/product-ceramic_pot.jpg",
},
{
    id:68,
    title: 'Handmade man necklace',
    price: 40,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-necklace.jpg",
},
{
    id:69,
    title: 'Handmade man necklace',
    price: 45,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-necklace.jpg",
},
{
    id:70,
    title: 'Handmade man necklace',
    price: 50,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-necklace.jpg",
},
{
    id:71,
    title: 'Handmade man necklace',
    price: 60,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-necklace.jpg",
},
{
    id:72,
    title: 'Handmade man necklace',
    price: 65,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-necklace.jpg",
},
{
    id:73,
    title: 'Handmade man necklace',
    price: 70,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-necklace.jpg",
},
{
    id:74,
    title: 'Handmade man necklace',
    price: 80,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-necklace.jpg",
},
{
    id:75,
    title: 'Handmade man necklace',
    price: 85,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-necklace.jpg",
},
{
    id:76,
    title: 'Handmade man necklace',
    price: 90,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-necklace.jpg",
},
{
    id:77,
    title: 'Seashell earrings',
    price: 80,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-seashell.jpg",
},
{
    id:78,
    title: 'Seashell earrings',
    price: 85,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-seashell.jpg",
},
{
    id:79,
    title: 'Seashell earrings',
    price: 90,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-seashell.jpg",
},
{
    id:80,
    title: 'Seashell earrings',
    price: 60,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-seashell.jpg",
},
{
    id:81,
    title: 'Seashell earrings',
    price: 65,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-seashell.jpg",
},
{
    id:82,
    title: 'Seashell earrings',
    price: 70,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-seashell.jpg",
},
{
    id:83,
    title: 'Seashell earrings',
    price: 40,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-seashell.jpg",
},
{
    id:84,
    title: 'Seashell earrings',
    price: 45,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-seashell.jpg",
},
{
    id:85,
    title: 'Seashell earrings',
    price: 50,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-seashell.jpg",
},
{
    id:86,
    title: 'Pearl and gold earrings',
    price: 80,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-pear&gold.jpg",
},
{
    id:87,
    title: 'Pearl and gold earrings',
    price: 85,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-pear&gold.jpg",
},
{
    id:88,
    title: 'Pearl and gold earrings',
    price: 90,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-pear&gold.jpg",
},
{
    id:89,
    title: 'Pearl and gold earrings',
    price: 60,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-pear&gold.jpg",
},
{
    id:90,
    title: 'Pearl and gold earrings',
    price: 65,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-pear&gold.jpg",
},
{
    id:91,
    title: 'Pearl and gold earrings',
    price: 70,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-pear&gold.jpg",
},
{
    id:92,
    title: 'Pearl and gold earrings',
    price: 40,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-pear&gold.jpg",
},
{
    id:93,
    title: 'Pearl and gold earrings',
    price: 45,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-pear&gold.jpg",
},
{
    id:94,
    title: 'Pearl and gold earrings',
    price: 50,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-pear&gold.jpg",
},
{
    id:95,
    title: 'Handmade necklace',
    price: 80,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-handmade_necklace.jpg",
},
{
    id:96,
    title: 'Handmade necklace',
    price: 85,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-handmade_necklace.jpg",
},
{
    id:97,
    title: 'Handmade necklace',
    price: 90,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-handmade_necklace.jpg",
},
{
    id:98,
    title: 'Handmade necklace',
    price: 60,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-handmade_necklace.jpg",
},
{
    id:99,
    title: 'Handmade necklace',
    price: 65,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-handmade_necklace.jpg",
},
{
    id:100,
    title: 'Handmade necklace',
    price: 70,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-handmade_necklace.jpg",
},
{
    id:101,
    title: 'Handmade necklace',
    price: 40,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-handmade_necklace.jpg",
},
{
    id:102,
    title: 'Handmade necklace',
    price: 45,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-handmade_necklace.jpg",
},
{
    id:103,
    title: 'Handmade necklace',
    price: 50,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-handmade_necklace.jpg",
},
{
    id:104,
    title: 'Man necklace',
    price: 80,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-man_necklace.jpg",
},
{
    id:105,
    title: 'Man necklace',
    price: 85,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-man_necklace.jpg",
},
{
    id:106,
    title: 'Man necklace',
    price: 90,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-man_necklace.jpg",
},
{
    id:107,
    title: 'Man necklace',
    price: 60,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-man_necklace.jpg",
},
{
    id:108,
    title: 'Man necklace',
    price: 65,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-man_necklace.jpg",
},
{
    id:109,
    title: 'Man necklace',
    price: 70,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-man_necklace.jpg",
},
{
    id:110,
    title: 'Man necklace',
    price: 40,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-man_necklace.jpg",
},
{
    id:111,
    title: 'Man necklace',
    price: 45,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-man_necklace.jpg",
},
{
    id:112,
    title: 'Man necklace',
    price: 50,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-man_necklace.jpg",
},
{
    id:113,
    title: 'Wood ring',
    price: 80,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-wood_ring.jpg",
},
{
    id:114,
    title: 'Wood ring',
    price: 85,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-wood_ring.jpg",
},
{
    id:115,
    title: 'Wood ring',
    price: 90,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Gold',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-wood_ring.jpg",
},
{
    id:116,
    title: 'Wood ring',
    price: 60,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-wood_ring.jpg",
},
{
    id:117,
    title: 'Wood ring',
    price: 65,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-wood_ring.jpg",
},
{
    id:118,
    title: 'Wood ring',
    price: 70,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Platinum',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-wood_ring.jpg",
},
{
    id:119,
    title: 'Wood ring',
    price: 40,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '35cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-wood_ring.jpg",
},
{
    id:120,
    title: 'Wood ring',
    price: 45,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '40cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-wood_ring.jpg",
},
{
    id:121,
    title: 'Wood ring',
    price: 50,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    material: 'Silver',
    length: '45cm',
    stock: 50,
    categories: 'jewels',
    image: "/images/product-wood_ring.jpg",
},
{
    id:122,
    title: 'Tropical plant',
    price: 15,
    rating: 5,
    describtion: "Quisque velit nisi, pretium ut lacinia in, elementum id enim. Pellentesque in ipsum id orci porta dapibus.",
    categories: 'plants',
    image: "/images/product-tropical.jpg",
},
{
    id:123,
    title: 'Small terrarium',
    price: 15,
    rating: 5,
    describtion: "Quisque velit nisi, pretium ut lacinia in, elementum id enim. Pellentesque in ipsum id orci porta dapibus.",
    categories: 'plants',
    image: "/images/product-smterrarium.jpg",
},
{
    id:124,
    title: 'Small plant',
    price: 15,
    rating: 5,
    describtion: "Quisque velit nisi, pretium ut lacinia in, elementum id enim. Pellentesque in ipsum id orci porta dapibus.",
    categories: 'plants',
    image: "/images/product-smplant.jpg",
},
{
    id:125,
    title: 'Christmas ornaments #1',
    price: 15,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '2pcks',
    color: 'blue',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-1.jpg",
},
{
    id:126,
    title: 'Christmas ornaments #1',
    price: 20,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '3pcks',
    color: 'blue',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-1.jpg",
},
{
    id:127,
    title: 'Christmas ornaments #1',
    price: 25,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '4pcks',
    color: 'blue',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-1.jpg",
},
{
    id:128,
    title: 'Christmas ornaments #1',
    price: 15,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '2pcks',
    color: 'gold',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-1.jpg",
},
{
    id:129,
    title: 'Christmas ornaments #1',
    price: 20,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '3pcks',
    color: 'gold',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-1.jpg",
},
{
    id:130,
    title: 'Christmas ornaments #1',
    price: 25,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '4pcks',
    color: 'gold',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-1.jpg",
},
{
    id:131,
    title: 'Christmas ornaments #1',
    price: 15,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '2pcks',
    color: 'purple',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-1.jpg",
},
{
    id:132,
    title: 'Christmas ornaments #1',
    price: 20,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '3pcks',
    color: 'purple',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-1.jpg",
},
{
    id:133,
    title: 'Christmas ornaments #1',
    price: 25,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '4pcks',
    color: 'purple',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-1.jpg",
},
{
    id:134,
    title: 'Christmas ornaments #2',
    price: 15,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '2pcks',
    color: 'blue',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-2.jpg",
},
{
    id:135,
    title: 'Christmas ornaments #2',
    price: 20,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '3pcks',
    color: 'blue',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-2.jpg",
},
{
    id:136,
    title: 'Christmas ornaments #2',
    price: 25,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '4pcks',
    color: 'blue',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-2.jpg",
},
{
    id:137,
    title: 'Christmas ornaments #2',
    price: 15,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '2pcks',
    color: 'gold',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-2.jpg",
},
{
    id:138,
    title: 'Christmas ornaments #2',
    price: 20,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '3pcks',
    color: 'gold',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-2.jpg",
},
{
    id:139,
    title: 'Christmas ornaments #2',
    price: 25,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '4pcks',
    color: 'gold',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-2.jpg",
},
{
    id:140,
    title: 'Christmas ornaments #2',
    price: 15,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '2pcks',
    color: 'purple',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-2.jpg",
},
{
    id:141,
    title: 'Christmas ornaments #2',
    price: 20,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '3pcks',
    color: 'purple',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-2.jpg",
},
{
    id:142,
    title: 'Christmas ornaments #2',
    price: 25,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '4pcks',
    color: 'purple',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-2.jpg",
},
{
    id:143,
    title: 'Christmas ornaments #3',
    price: 15,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '2pcks',
    color: 'blue',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-3.jpg",
},
{
    id:144,
    title: 'Christmas ornaments #3',
    price: 20,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '3pcks',
    color: 'blue',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-3.jpg",
},
{
    id:145,
    title: 'Christmas ornaments #3',
    price: 25,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '4pcks',
    color: 'blue',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-3.jpg",
},
{
    id:146,
    title: 'Christmas ornaments #3',
    price: 15,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '2pcks',
    color: 'gold',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-3.jpg",
},
{
    id:147,
    title: 'Christmas ornaments #3',
    price: 20,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '3pcks',
    color: 'gold',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-3.jpg",
},
{
    id:148,
    title: 'Christmas ornaments #3',
    price: 25,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '4pcks',
    color: 'gold',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-3.jpg",
},
{
    id:149,
    title: 'Christmas ornaments #3',
    price: 15,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '2pcks',
    color: 'purple',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-3.jpg",
},
{
    id:150,
    title: 'Christmas ornaments #3',
    price: 20,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '3pcks',
    color: 'purple',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-3.jpg",
},
{
    id:151,
    title: 'Christmas ornaments #3',
    price: 25,
    rating: 5,
    describtion: "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui. Vivamus magna justo, lacinia eget consectetur sed, convallis at tellus.",
    pack: '4pcks',
    color: 'purple',
    stock: 10,
    categories: 'decor',
    image: "/images/product-christmas_ornaments-3.jpg",
},
]

// stock in the all categories, havent one category plant

export const getProductsObject = (array: Product[]) => 
array.reduce((object, product)=>({...object, [product.id]: product,}),{})

export default productsArray